### ISSUE TITLE
How is it licensed?

### ISSUE THREAD

**Issue by moon-chilled** [milesmcc/whyprivacymatters#1]
At the end of REASONS.md there's some text: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."  But there's a LICENSE file that's the MIT license.  So, which is it?

**Comment by milesmcc** [comment]
So the actual markdown files (and the actual code which will accompany them, when we actually build the website) are licensed MIT, however the TEXT of the reasons is licensed CC.

Does this make sense, or should I change?

**Comment by milesmcc** [comment]
@Elronnd — your thoughts?

Edit: the project is very unambiguously CC-BY-SA 4.0 now. Issue closed. Feel free to reopen if you disagree.
