### ISSUE TITLE
Improve privacy on your site, by removing dependencies on 3rd party assets

### ISSUE THREAD

**Issue by marinkol** [milesmcc/whyprivacymatters#14]
**Issue type:** Request for Improvement

**Short description:** Remove 3rd party assets on your web page

**Observed:** When one loads https://whyprivacymatters.org/ It loads assets form 6 other 3rd party websites

https://fonts.googleapis.com/css?family=IBM+Plex+Mono:700|IBM+Plex+Sans&subset=cyrillic,cyrillic-ext,latin-ext,vietnamese
https://code.jquery.com/jquery-3.3.1.slim.min.js
https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js
https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js
https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.woff2
https://use.fontawesome.com/releases/v5.2.0/css/all.css
https://fonts.gstatic.com/s/ibmplexsans/v7/zYXgKVElMYYaJe8bpLHnCwDKhdHeFQ.woff2
https://fonts.gstatic.com/s/ibmplexsans/v7/zYXgKVElMYYaJe8bpLHnCwDKhdHeFQ.woff2

I know that this might seem low impact (and it is), but if even the privacy focused sites can't be bothered to limit their dependencies and not linking to google api's (and others) there is little hope for the rest of the web.

Considering this is static, mostly text page focusing on privacy, It shouldn't be that difficult to get message across without those 3rd party assets.

**Comment by milesmcc** [comment]
Yes, you're right—this is a great opportunity for improvement. I don't have a ton of time on my hands right now, but if you think you or anyone else could put together a PR doing this I'd merge it immediately!
