### ISSUE TITLE
Add localised links to EFF's guide

### ISSUE THREAD

**Issue by gordonel** [milesmcc/whyprivacymatters#20]
**Issue type:** other
**Short description:** Guide links point to https://ssd.eff.org/, which could cause people stop reading because they can't read English
**Expected:** The links point to an appropriate localised (translated) version of the EFF guide
**Observed:** The links point to an English version
**Long description:**
Short description basically says it all. We can point some translated pages to their counterparts in the appropriate language. Also, depending on the region, we might point to a language with a high degree of mutual intelligibility or exposure. For example, many Ukrainians have enough exposure to Russian to understand it without issues (@ibarakaiev can correct me if I am wrong)

**Comment by milesmcc** [comment]
I think this is a very good idea. I'm not sure I have the time to build this in right now, but if you want to submit this as a PR I will happily accept it.

Either way, I'll add it to the roadmap in the longer term.

**Comment by gordonel** [comment]
See #22 . I decided not to play mix and match with links at this time. Maybe I'll offer to translate EFF guide to a few languages I know and link them here afterwards
