### ISSUE TITLE
Create localised domains

### ISSUE THREAD

**Issue by gordonel** [milesmcc/whyprivacymatters#21]
**Issue type:** other
**Short description:** people may search for "why privacy matters" in other language and have trouble finding the website
**Long description:**
It would probably increase the costs associated with the project, but having region-specific domains for translated pages would be beneficial. I had trouble finding the website by searching `Pourquoi la vie privée est importante` in French Google, for instance. Having region-appropriate domains might boost the SEO stance of the message and help it go up in search results.

**Comment by milesmcc** [comment]
Wow! That would be... quite expensive. We do currently set the `lang` attribute of the translated pages, so ideally search engines will control for that, but you're right that this would probably help. Unfortunately, I don't think this is feasible given the cost required in acquiring all those domains.

If you have any ideas for ways to drive more traffic to the site, though, let me know!
